DROP TABLE IF EXISTS channel CASCADE;
DROP TABLE IF EXISTS playlist CASCADE;
DROP TABLE IF EXISTS video CASCADE;
DROP TABLE IF EXISTS playlist_videos CASCADE;
DROP TABLE IF EXISTS statistics CASCADE;
DROP TABLE IF EXISTS company CASCADE;
DROP TABLE IF EXISTS link CASCADE;
DROP TABLE IF EXISTS blacklisted_link CASCADE;
