INSERT INTO blacklisted_link(value, channel_id) VALUES
                                                    ('http://facebook.com/UsachevShow','UCDaIW2zPRWhzQ9Hj7a0QP1w'),
                                                    ('http://twitter.com/RuslanUsachev', 'UCDaIW2zPRWhzQ9Hj7a0QP1w'),
                                                    ('http://vk.com/UsachevShow','UCDaIW2zPRWhzQ9Hj7a0QP1w'),
                                                    ('https://vk.com/UsachevShow', 'UCDaIW2zPRWhzQ9Hj7a0QP1w'),
                                                    ('https://twitter.com/RuslanUsachev','UCDaIW2zPRWhzQ9Hj7a0QP1w'),
                                                    ('https://facebook.com/UsachevShow', 'UCDaIW2zPRWhzQ9Hj7a0QP1w'),
                                                    ('http://vkontakte.ru/usachevshow','UCDaIW2zPRWhzQ9Hj7a0QP1w'),
                                                    ('https://vkontakte.ru/usachevshow', 'UCDaIW2zPRWhzQ9Hj7a0QP1w'),
                                                    ('http://usachevshow.livejournal.com/','UCDaIW2zPRWhzQ9Hj7a0QP1w'),
                                                    ('http://vkontakte.ru/questions.php', 'UCDaIW2zPRWhzQ9Hj7a0QP1w'),
                                                    ('http://usachevshow.rutube.ru/','UCDaIW2zPRWhzQ9Hj7a0QP1w'),
                                                    ('https://usachevshow.rutube.ru/', 'UCDaIW2zPRWhzQ9Hj7a0QP1w'),
                                                    ('http://vkontakte.ru/club18403220','UCDaIW2zPRWhzQ9Hj7a0QP1w'),
                                                    ('https://vkontakte.ru/club18403220', 'UCDaIW2zPRWhzQ9Hj7a0QP1w'),
                                                    ('http://vkontakte.ru/UsachevShow','UCDaIW2zPRWhzQ9Hj7a0QP1w'),
                                                    ('https://vkontakte.ru/UsachevShow', 'UCDaIW2zPRWhzQ9Hj7a0QP1w'),
                                                    ('http://google.com/','UCDaIW2zPRWhzQ9Hj7a0QP1w'),
                                                    ('https://google.com/', 'UCDaIW2zPRWhzQ9Hj7a0QP1w'),
                                                    ('https://fb.com/UsachevRuslan','UCDaIW2zPRWhzQ9Hj7a0QP1w'),
                                                    ('http://fb.com/UsachevRuslan', 'UCDaIW2zPRWhzQ9Hj7a0QP1w'),
                                                    ('http://instagram.com/UsachevRuslan','UCDaIW2zPRWhzQ9Hj7a0QP1w'),
                                                    ('https://instagram.com/UsachevRuslan', 'UCDaIW2zPRWhzQ9Hj7a0QP1w'),
                                                    ('https://vk.com/UsachevRuslan','UCDaIW2zPRWhzQ9Hj7a0QP1w'),
                                                    ('http://youtu.be/VkxVemgNEaA', 'UCDaIW2zPRWhzQ9Hj7a0QP1w'),
                                                    ('http://youtu.be/DGNxHa0bqCI','UCDaIW2zPRWhzQ9Hj7a0QP1w'),
                                                    ('http://youtu.be/OK7pfLlsUQM', 'UCDaIW2zPRWhzQ9Hj7a0QP1w'),
                                                    ('http://www.youtube.com/watch','UCDaIW2zPRWhzQ9Hj7a0QP1w'),
                                                    ('http://vk.com/event34842361', 'UCDaIW2zPRWhzQ9Hj7a0QP1w'),
                                                    ('http://youtu.be/oMREA_XLQ1A','UCDaIW2zPRWhzQ9Hj7a0QP1w'),
                                                    ('http://youtu.be/DkjrOssNAEc', 'UCDaIW2zPRWhzQ9Hj7a0QP1w'),
                                                    ('http://www.youtube.com/MeshokShishek','UCDaIW2zPRWhzQ9Hj7a0QP1w'),
                                                    ('http://video.rosbalt.ru/view_video.php', 'UCDaIW2zPRWhzQ9Hj7a0QP1w'),
                                                    ('http://lenta.ru/news/2012/04/17/semerka/','UCDaIW2zPRWhzQ9Hj7a0QP1w'),
                                                    ('http://tech.onliner.by/2012/04/17/tupac-shakur', 'UCDaIW2zPRWhzQ9Hj7a0QP1w'),
                                                    ('http://habrahabr.ru/post/142763/', 'UCDaIW2zPRWhzQ9Hj7a0QP1w'),
                                                    ('http://youtu.be/KaOxGx2GZvE','UCDaIW2zPRWhzQ9Hj7a0QP1w'),
                                                    ('http://www.kinopoisk.ru/level/2/news/1847839/', 'UCDaIW2zPRWhzQ9Hj7a0QP1w'),
                                                    ('http://tengrinews.kz/kazakhstan_news/212721/','UCDaIW2zPRWhzQ9Hj7a0QP1w'),
                                                    ('http://rsport.ru/video/20120416/591996442.html', 'UCDaIW2zPRWhzQ9Hj7a0QP1w'),
                                                    ('http://habrahabr.ru/company/sonyxperia/blog/139843/', 'UCDaIW2zPRWhzQ9Hj7a0QP1w'),
                                                    ('http://www.rbcdaily.ru/2012/05/02/market/562949983718888','UCDaIW2zPRWhzQ9Hj7a0QP1w'),
                                                    ('http://www.izvestia.ru/news/523639', 'UCDaIW2zPRWhzQ9Hj7a0QP1w'),
                                                    ('http://www.lifenews.ru/news/89399','UCDaIW2zPRWhzQ9Hj7a0QP1w'),
                                                    ('http://lenta.ru/news/2012/05/02/queen/', 'UCDaIW2zPRWhzQ9Hj7a0QP1w'),
                                                    ('http://top.rbc.ru/society/11/05/2012/649813.shtml', 'UCDaIW2zPRWhzQ9Hj7a0QP1w'),
                                                    ('http://www.3dnews.ru/software-news/629166/','UCDaIW2zPRWhzQ9Hj7a0QP1w'),
                                                    ('http://oleganisimov.livejournal.com/424124.html', 'UCDaIW2zPRWhzQ9Hj7a0QP1w'),
                                                    ('http://top.rbc.ru/wildworld/21/05/2012/651269.shtml','UCDaIW2zPRWhzQ9Hj7a0QP1w'),
                                                    ('http://dgudkov.livejournal.com/181257.html', 'UCDaIW2zPRWhzQ9Hj7a0QP1w'),
                                                    ('http://slon.ru/russia/pravitelstvo_neprofessionalov-791549.xhtml', 'UCDaIW2zPRWhzQ9Hj7a0QP1w'),
                                                    ('http://usachevshow','UCDaIW2zPRWhzQ9Hj7a0QP1w'),
                                                    ('http://top.rbc.ru/politics/18/06/2012/655433.shtml', 'UCDaIW2zPRWhzQ9Hj7a0QP1w'),
                                                    ('http://www.cnews.ru/news/line/print.shtml','UCDaIW2zPRWhzQ9Hj7a0QP1w'),
                                                    ('http://ria.ru/beznarko_danger/20120704/691406349.html', 'UCDaIW2zPRWhzQ9Hj7a0QP1w'),
                                                    ('http://mashable.com/2012/07/01/20-under-20-transforming-tomorrow/', 'UCDaIW2zPRWhzQ9Hj7a0QP1w'),
                                                    ('http://marker.ru/news/529344','UCDaIW2zPRWhzQ9Hj7a0QP1w'),
                                                    ('http://gazaryan-suren.livejournal.com/91653.html', 'UCDaIW2zPRWhzQ9Hj7a0QP1w'),
                                                    ('https://t.me/usachevruslan','UCDaIW2zPRWhzQ9Hj7a0QP1w'),
                                                    ('https://zen.yandex.ru/usachevruslan', 'UCDaIW2zPRWhzQ9Hj7a0QP1w'),
                                                    ('ttps://telegra.ph/Otkrytoe-pismo-YUriya-Hovanskogo-11-29','UCDaIW2zPRWhzQ9Hj7a0QP1w'),
                                                    ('https://rarible.com/usachevruslan', 'UCDaIW2zPRWhzQ9Hj7a0QP1w'),
                                                    ('https://www.gq.ru/awards/moty/2021/screen-man-2021','UCDaIW2zPRWhzQ9Hj7a0QP1w'),
                                                    ('https://youtu.be/xC6J4T_hUKg', 'UCDaIW2zPRWhzQ9Hj7a0QP1w'),
                                                    ('https://teleg.run/usachevruslan','UCDaIW2zPRWhzQ9Hj7a0QP1w'),
                                                    ('https://youtu.be/wzFLmoDyemA', 'UCDaIW2zPRWhzQ9Hj7a0QP1w'),
                                                    ('https://youtu.be/PGdfhZve-HI','UCDaIW2zPRWhzQ9Hj7a0QP1w'),
                                                    ('https://youtu.be/aQRWi2My7KE', 'UCDaIW2zPRWhzQ9Hj7a0QP1w'),
                                                    ('https://youtu.be/KtL-gNxDBGI','UCDaIW2zPRWhzQ9Hj7a0QP1w'),
                                                    ('https://www.youtube.com/biggeekru', 'UCDaIW2zPRWhzQ9Hj7a0QP1w'),
                                                    ('https://www.youtube.com/usachevShow','UCDaIW2zPRWhzQ9Hj7a0QP1w'),
                                                    ('https://www.youtube.com/channel/UCfOMwpnqvDj49hTicfmhKDg', 'UCDaIW2zPRWhzQ9Hj7a0QP1w'),
                                                    ('https://www.instagram.com/p/BrvXvAIFSmz/','UCDaIW2zPRWhzQ9Hj7a0QP1w');